### ISSUE TITLE
Problem with multiple CF7 forms on one page

### ISSUE THREAD

**Issue by wpre** [bootscore/bs-contact-form-7#3]
if you have multiple cf7 forms on a page. The JS file inserts also an empty alert box to the not used contact form. How can we display alerts only on the used contact form? 

Thanks in advance.

**Comment by crftwrk** [comment]
It's not possible to show more than one form in a page yet. Because alert is triggered by id and if you have two forms on the same site, the id is double. But we planned already move support for CF7 to theme with a different approach and no js.

You can use WS Form https://bootscore.me/plugins/ws-form/ instead. With this it's possible to show multiple Forms on a site. Lite version is free https://wordpress.org/plugins/ws-form/.

**Comment by wpre** [comment]
Thanks for the quick response, since I want to use CF7, I coded this workaround which is working fine: 

example shortcode with html_id: 

`[contact-form-7 id="7" title="Kontakt" html_id="aa-7"]`

example alertbox addclass to the specific form which is used: 

```
document.addEventListener('wpcf7invalid', function (event) {
       $('#aa-'+event.detail.contactFormId+' .wpcf7-response-output').addClass('alert alert-danger');
}, false);
```
